apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-deployment
spec:
  selector:
    matchLabels:
      app: history-api
  replicas: 3
  template:
    metadata:
      labels:
        app: history-api
    spec:
      containers:
        - name: history
          image: history:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
spec:
  type: NodePort
  selector:
    app: history-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: history-ingress
spec:
  rules:
    - host: history-api.xxx.xxx
      http:
        paths:
          - path: /
            backend:
              serviceName: history-service
              servicePort: 80